stages:
  update-sql:
    actions:
      - type: liquibase
        command: UpdateSQL
        cmdArgs: {changeLogFile: changelog/changelog.xml}
        properties: liquibase.properties
  
  update:
    actions:
      - type: liquibase
        command: Update
        cmdArgs: {changeLogFile: changelog/changelog.xml}
        properties: liquibase.properties

endstage:
    actions:
      - type: liquibase
        command: History
        cmdArgs: {verbose: true, changeLogFile: changelog/changelog.xml}
        properties: liquibase.properties