# JDBC connection settings
#url=hashicorp,${vaultPath},url
#username=hashicorp,${vaultPath},username
#password=hashicorp,${vaultPath},password
url=jdbc:mysql://mysql-avinash.alwaysdata.net:3306/avinash
username=avinash
password=A@vinash2412
driver=${driver}
changeLogFile=changelog/changelog.xml
# Logging
logLevel=info
vault.addr=${vaultAddress}
vault.namespace=${vaultNS}


