name: Liquibase Migration

on:
  workflow_call:
    inputs:
      db_host:
        required: true
        type: string
      db_port:
        required: true
        type: string
      db_name:
        required: true
        type: string
      db_user:
        required: true
        type: string
      db_pass:
        required: true
        type: string
      changelog_file:
        required: false
        type: string
        default: changelog/changelog.xml

jobs:
  liquibase-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Liquibase
        run: |
          wget https://github.com/liquibase/liquibase/releases/download/v4.33.0/liquibase-4.33.0.zip
          mkdir -p /opt/liquibase
          unzip liquibase-4.33.0.zip -d /opt/liquibase
          echo "/opt/liquibase" >> $GITHUB_PATH
          ls -l /opt/liquibase  # Debug

      - name: Download MySQL JDBC Driver
        run: |
          wget -O /opt/liquibase/lib/mysql-connector-j-9.3.0.jar \
            https://repo1.maven.org/maven2/com/mysql/mysql-connector-j/9.3.0/mysql-connector-j-9.3.0.jar
          ls -l /opt/liquibase/lib

      - name: Run Liquibase Update
        run: |
          liquibase \
            --url="jdbc:mysql://${{ inputs.db_host }}:${{ inputs.db_port }}/${{ inputs.db_name }}" \
            --username="${{ inputs.db_user }}" \
            --password="${{ inputs.db_pass }}" \
            --changeLogFile=${{ inputs.changelog_file }} \
            update
