name: Liquibase MySQL Migration

on:
  push:
    branches: [ main ]

jobs:
  liquibase-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: setup liquibase
        run: |
          wget https://github.com/liquibase/liquibase/releases/download/v4.33.0/liquibase-4.33.0.zip
          mkdir -p /opt/liquibase
          unzip liquibase-4.33.0.zip -d /opt/liquibase
          echo "/opt/liquibase" >> $GITHUB_PATH
          ls -l /opt/liquibase  # Debug: confirm extraction

      - name: Download MySQL JDBC Driver
        run: |
          liquibase --version
          mkdir -p lib
          wget https://repo1.maven.org/maven2/mysql/mysql-connector-j/8.0.30/mysql-connector-j-8.0.30.jar -o /home/runner/work/liquibase_actions/liquibase_actions/lib/mysql-connector-j-8.0.30.jar

      - name: Run Liquibase Update
        run: |
          liquibase \
            --classpath=lib/mysql-connector-j-8.0.30.jar \
            --url="jdbc:mysql://localhost:3300/onlinebookstore" \
            --username=root \
            --password=root \
            --changeLogFile=changelog/changelog.xml \
            update
