name: Liquibase Reusable Action

on:
  workflow_call:
    inputs:
      changeLogFile:
        required: true
        type: string
      cd_flowfile:
        required: false
        type: string
      ci_flowfile:
        required: false
        type: string

jobs:
  liquibase-Execution:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Liquibase
        run: |
          wget https://github.com/liquibase/liquibase/releases/download/v4.33.0/liquibase-4.33.0.zip
          unzip liquibase-4.33.0.zip -d liquibase
          echo "$PWD/liquibase" >> $GITHUB_PATH

      # 🔥 Restore truststore
      - name: Setup Truststore
        run: |
          echo "${{ secrets.SNOWFLAKE_TRUSTSTORE_BASE64 }}" | base64 -d > truststore.jks

      # 🔥 Set SSL
      - name: Set JAVA_OPTS
        run: |
          echo "JAVA_OPTS=-Djavax.net.ssl.trustStore=$PWD/truststore.jks -Djavax.net.ssl.trustStorePassword=${{ secrets.SNOWFLAKE_TRUSTSTORE_PASSWORD }}" >> $GITHUB_ENV

      # 🔥 Create liquibase.properties
      - name: Create liquibase.properties
        run: |
          cat <<EOF > liquibase.properties
          url=${{ secrets.SNOWFLAKE_URL }}
          username=${{ secrets.SNOWFLAKE_USERNAME }}
          password=${{ secrets.SNOWFLAKE_PASSWORD }}
          driver=net.snowflake.client.jdbc.SnowflakeDriver
          EOF

      # CI Flow
      - name: Run Liquibase CI Flow
        if: ${{ inputs.ci_flowfile != '' }}
        run: |
          liquibase --changeLogFile=${{ inputs.changeLogFile }} flow --flow-file=${{ inputs.ci_flowfile }}

      # CD Flow
      - name: Run Liquibase CD Flow
        if: ${{ inputs.cd_flowfile != '' }}
        run: |
          liquibase --changeLogFile=${{ inputs.changeLogFile }} flow --flow-file=${{ inputs.cd_flowfile }}

      # Rollback
      - name: Rollback Liquibase CD
        if: failure() && inputs.cd_flowfile != ''
        run: |
          liquibase --changeLogFile=${{ inputs.changeLogFile }} rollbackCount 1
