name: Liquibase Migration

on:
  push:
    branches:
      - main   # Run when changes are pushed to main
  workflow_dispatch:   # Allow manual trigger

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - uses: liquibase/setup-liquibase@v1
        with:
            version: '4.33.0'
            edition: 'oss'
      - run: ls -lrt /home/runner/work/liquibase_actions/liquibase_actions/lib/

      - name: Run Liquibase Update
        env:
          LB_URL: ${{ secrets.LB_URL }}
          LB_USERNAME: ${{ secrets.LB_USERNAME }}
          LB_PASSWORD: ${{ secrets.LB_PASSWORD }}
        run: |
          liquibase \
            --url=$LB_URL \
            --username=$LB_USERNAME \
            --password=$LB_PASSWORD \
            --changelog-file=changelog/changelog.xml \
            update
