name: Liquibase Reusable Action
description: This workflow runs Liquibase to build artifact.

on:
  workflow_call:
    inputs:
      changeLogFile:
        description: 'Path to the changelog file'
        required: true
        type: string

      cd_flowfile:
        description: 'Path to the CD flowfile'
        required: false
        type: string

      ci_flowfile:
        description: 'Path to the CI flowfile'
        required: false
        type: string
  

jobs:
  liquibase-Execution:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Liquibase
        run: |
          wget https://github.com/liquibase/liquibase/releases/download/v4.33.0/liquibase-4.33.0.zip
          mkdir -p /opt/liquibase
          unzip liquibase-4.33.0.zip -d /opt/liquibase
          echo "/opt/liquibase" >> $GITHUB_PATH
          ls -l /opt/liquibase  # Debug

      - name: Download JDBC + Vault Extensions
        run: |
          wget -O /opt/liquibase/lib/mysql-connector-j-9.3.0.jar \
            https://repo1.maven.org/maven2/com/mysql/mysql-connector-j/9.3.0/mysql-connector-j-9.3.0.jar
          wget -O /opt/liquibase/lib/liquibase-hashicorp-vault-2.0.5.jar \
            https://repo1.maven.org/maven2/org/liquibase/ext/vaults/liquibase-hashicorp-vault/2.0.5/liquibase-hashicorp-vault-2.0.5.jar

      - name: Get Vault Token
        run: |
          VAULT_ADDR="https://vault-cluster-public-vault-1fd3489a.8cdec62c.z1.hashicorp.cloud:8200"
          VAULT_NAMESPACE="admin/liquibase"

          RESPONSE=$(sudo curl -s --header "X-Vault-Namespace: $VAULT_NAMESPACE" \
            --request POST \
            --data '{"role_id": "df4a1f0d-b3c7-6013-4185-350150e44290", "secret_id": "372b9737-683c-9898-c267-40c77c3367c6"}' \
            $VAULT_ADDR/v1/auth/approle/login)

          echo "Raw response: $RESPONSE"

          VAULT_TOKEN=$(echo "$RESPONSE" | jq -r '.auth.client_token')

          if [ "$VAULT_TOKEN" != "null" ] && [ -n "$VAULT_TOKEN" ]; then
            # Important: use sudo tee so root can write into $GITHUB_ENV
            echo "vault.token=$VAULT_TOKEN" | sudo tee -a $GITHUB_ENV
            echo "vault.addr=$VAULT_ADDR" | sudo tee -a $GITHUB_ENV
            echo "vault.namespace=$VAULT_NAMESPACE" | sudo tee -a $GITHUB_ENV
          else
            echo "❌ Failed to fetch Vault token!"
            exit 1
          fi
      # Run CI flow if provided
      - name: Run Liquibase CI Flow
        if: ${{ inputs.ci_flowfile != '' }}
        run: |
          liquibase \
            --changeLogFile=${{ inputs.changeLogFile }} \
            flow \
            --flow-file=${{ inputs.ci_flowfile }} \
            --logLevel=info

      # Run CD flow if provided
      - name: Run Liquibase CD Flow
        if: ${{ inputs.cd_flowfile != '' }}
        run: |
          liquibase \
            --changeLogFile=${{ inputs.changeLogFile }} \
            flow \
            --flow-file=${{ inputs.cd_flowfile }} \
            --logLevel=info

      # Rollback for CD only
      - name: Rollback Liquibase CD
        if: failure() && inputs.cd_flowfile != ''
        run: |
          liquibase \
            --changeLogFile=${{ inputs.changeLogFile }} \
            rollbackCount 1 \
            --logLevel=info
