name: Liquibase MySQL Migration

on:
  push:
    branches: [ main ]

jobs:
  liquibase-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: setup liquibase
        uses: liquibase/setup-liquibase@v1
        with:
          version: 4.33.0
          edition: 'oss'
          
      - name: Download MySQL JDBC Driver
        run: |
          liquibase --version
          mkdir -p lib
          wget https://repo1.maven.org/maven2/mysql/mysql-connector-j/8.0.30/mysql-connector-j-8.0.30.jar -o lib/mysql-connector-j-8.0.30.jar

      - name: Run Liquibase Update
        run: |
          liquibase \
            --classpath=lib/mysql-connector-j-8.0.30.jar \
            --url="jdbc:mysql://localhost:3300/onlinebookstore" \
            --username=root \
            --password=root \
            --changeLogFile=changelog/changelog.xml \
            update
