name: liquibase CI/CD Deployment

on:
  workflow_dispatch:
    inputs:
      changeLogFile:
        description: 'Path to the changelog file'
        required: true
        default: 'changelog/changelog.xml'

      mode:
        description: 'Choose mode: CI or CD'
        required: true
        default: 'CI'
        type: choice
        options:
          - CI
          - CD

jobs:
  liquibase:
    uses: ./.github/workflows/liquibase_reusable_ci_action.yaml
    with:
      changeLogFile: ${{ inputs.changeLogFile }}
      ci_flowfile: ${{ inputs.mode == 'CI' && 'liquibase-ci.flowfile.yaml' || '' }}
      cd_flowfile: ${{ inputs.mode == 'CD' && 'liquibase-cd.flowfile.yaml' || '' }}
