name: Liquibase MySQL Migration

on:
  workflow_call:
    inputs:
      changelog:
        required: true
        type: string
        description: "Path to Liquibase changelog file (e.g., changelog.xml)"
      url:
        required: true
        type: string
        description: "JDBC URL for MySQL (e.g., jdbc:mysql://localhost:3306/testdb)"
      username:
        required: true
        type: string
        description: "Database username"
      password:
        required: true
        type: string
        description: "Database password"
    secrets:
      mysql_password:
        required: false

jobs:
  liquibase:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Install Liquibase
        run: |
          curl -sL https://github.com/liquibase/liquibase/releases/download/v4.30.0/liquibase-4.30.0.tar.gz | tar xz
          sudo mv liquibase /opt/liquibase
          sudo ln -s /opt/liquibase/liquibase /usr/local/bin/liquibase
          chmod +x /usr/local/bin/liquibase
          liquibase --version
          
      - name: Download MySQL JDBC driver
        run: |
          curl -L -o mysql-connector-j.jar https://repo1.maven.org/maven2/mysql/mysql-connector-j/8.0.30/mysql-connector-j-8.0.30.jar

      - name: Run Liquibase Update
        run: |
          liquibase \
            --changeLogFile=${{ inputs.changelog }} \
            --url=${{ inputs.url }} \
            --username=${{ inputs.username }} \
            --password=${{ inputs.password || secrets.mysql_password }} \
            --classpath=mysql-connector-j.jar \
            update
